apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: gp2-default-sc-remove
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    gp2-default-sc-remove:
      targetObjectRef:
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        name: gp2
      patchTemplate: |
        metadata:
          annotations: null
      patchType: application/strategic-merge-patch+json
