apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: self-prov-autoupdate
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    self-provisioner-autoupdate:
      targetObjectRef:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: self-provisioners
      patchTemplate: |
        metadata:
          annotations:
            rbac.authorization.kubernetes.io/autoupdate: "false"
        subjects: null
      patchType: application/strategic-merge-patch+json
